<a href="https://colab.research.google.com/github/davilaquinterosebastian-creator/Arreglos_12_08_2025/blob/main/vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5])
print(vector)
print(vector[2])
"""
los vectores no son como las append() para, agregar elementos o tienen un metodo pop()
para eliminar elementos, pero si tienen metodo reshape() para cambiar su forma.
adicionalmente, despues creado no se puede cambiar el tamaño del vector
"""
vector1 = np.zeros(5)  # crea un vector de ceros de tamaño 5
print(vector1)

vector2 = np.ones(5)   # crea un vector de unos de tamaño 5
print(vector2)

vector3 = np.arange(1,10)  # crea un vector con valores aleatorios entre 1 y 5
print("rango:", vector3)

vector4 = np.linspace(1, 10, 5)  # crea un vector con 5 valores igualmente espaciados entre 1 y 10
print("linspace:", vector4)

vector5 = np.random.rand(10) # crea un vector con 10 valores aleatorios entre 0 y 1
print("random:", vector5)

vector6 = np.random.randint(1, 100, 10) # crea un vector con 10 valores enteros aleatorios entre 1 y 100
print("randint:", vector6)


[1 2 3 4 5]
3
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
rango: [1 2 3 4 5 6 7 8 9]
linspace: [ 1.    3.25  5.5   7.75 10.  ]
random: [0.6849924  0.20027932 0.21360838 0.46196869 0.96970765 0.47135544
 0.25709755 0.91073803 0.47410784 0.05400539]
randint: [48 45 99 27 54 83 64 34 31 21]


los vectores son reservas de memoria para almacenar informacion, solo puede ser de un tipo,
si es numerico tiene que ser numerico, si es texto tiene que ser texto, esto aplica para las matrices.
Los arreglos son identificadores estaticos, esto significa que es otra forma de definir variables y
constantes
